steps:
- name: gcr.io/cloud-builders/gcloud
  id: 'Scp'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
     gcloud compute scp * main-instance:D:\Jeevan --zone asia-south1-c

steps:
- name: gcr.io/cloud-builders/gcloud
  id: 'Scp'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud compute snapshots create ${_snap_name} --project=hdfcergo-ci-cd-poc --source-disk=disk-1 --source-disk-zone=asia-south1-c --storage-location=asia-south1
  substitutions:
    _snap_name: 'snap-${BUILD_ID}'


