steps:
- name: gcr.io/cloud-builders/gcloud
  id: 'Scp'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
     gcloud compute scp * main-instance:D:\Jeevan --zone asia-south1-c

steps:
- name: gcr.io/cloud-builders/gcloud
  id: 'Scp'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud compute snapshots delete snapshot-disk


