steps:
- name: gcr.io/cloud-builders/gcloud
  id: 'Scp'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud compute scp * main-instance:D:\Jeevan --zone asia-south1-c

steps1:
- name: gcr.io/cloud-builders/gcloud
  id: 'Scp'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    substitutions:
      snap-name: echo $MY_RANDOM_NUMBER
    gcloud compute snapshots create ${snap-name} --project=hdfcergo-ci-cd-poc --source-disk=disk-1 --source-disk-zone=asia-south1-c --storage-location=asia-south1
